---
deployment:
  tasks:
    # TPQ Smart deployment
    - export DEPLOYPATH=/home/u1525344/tpqsmart/app
    - /bin/cp -r /home/u1525344/repositories/tpqsmart/app/Models $DEPLOYPATH
    - /bin/cp -r /home/u1525344/repositories/tpqsmart/app/Views $DEPLOYPATH
    - /bin/cp -r /home/u1525344/repositories/tpqsmart/app/Controllers $DEPLOYPATH
    - /bin/cp -r /home/u1525344/repositories/tpqsmart/app/Helpers $DEPLOYPATH
    - /bin/cp -r /home/u1525344/repositories/tpqsmart/app/Libraries $DEPLOYPATH
    - /bin/cp -r /home/u1525344/repositories/tpqsmart/app/Language $DEPLOYPATH
    - /bin/cp /home/u1525344/repositories/tpqsmart/app/Config/Routes.php $DEPLOYPATH/Config/
    - /bin/cp /home/u1525344/repositories/tpqsmart/app/Config/Autoload.php $DEPLOYPATH/Config/
    - /bin/cp /home/u1525344/repositories/tpqsmart/app/Config/Filters.php $DEPLOYPATH/Config/


    # Daftar Santri Baru deployment
    - export DEPLOYPATH=/home/u1525344/daftarsantribaru/app
    - /bin/cp -r /home/u1525344/repositories/tpqsmart/app/Views/backend/santri $DEPLOYPATH/Views/backend
    - /bin/cp /home/u1525344/repositories/tpqsmart/app/Views/backend/template/scripts.php $DEPLOYPATH/Views/backend/template
    - /bin/cp /home/u1525344/repositories/tpqsmart/app/Controllers/Backend/Santri.php $DEPLOYPATH/Controllers/Backend/
    - /bin/cp /home/u1525344/repositories/tpqsmart/app/Models/SantriBaruModel.php $DEPLOYPATH/Models/
