---
deployment:
  tasks:
    # TPQ Smart deployment
    - export DEPLOYPATH=/home/u1525344/tpqsmart/app
    # Copy composer.json dan composer.lock untuk dependency management
    - /bin/cp /home/u1525344/repositories/tpqsmart/composer.json /home/u1525344/tpqsmart/composer.json
    - /bin/cp /home/u1525344/repositories/tpqsmart/composer.lock /home/u1525344/tpqsmart/composer.lock
    # Install/Update Composer dependencies
    - cd /home/u1525344/tpqsmart && /opt/cpanel/composer/bin/composer install --no-dev --optimize-autoloader --quiet
    - /bin/cp -r /home/u1525344/repositories/tpqsmart/app/Models $DEPLOYPATH
    - /bin/cp -r /home/u1525344/repositories/tpqsmart/app/Views $DEPLOYPATH
    - /bin/cp -r /home/u1525344/repositories/tpqsmart/app/Controllers $DEPLOYPATH
    - /bin/cp -r /home/u1525344/repositories/tpqsmart/app/Helpers $DEPLOYPATH
    - /bin/cp -r /home/u1525344/repositories/tpqsmart/app/Libraries $DEPLOYPATH
    - /bin/cp -r /home/u1525344/repositories/tpqsmart/app/Language $DEPLOYPATH
    - /bin/cp -r /home/u1525344/repositories/tpqsmart/app/Authentication $DEPLOYPATH
    - /bin/cp /home/u1525344/repositories/tpqsmart/app/Config/Routes.php $DEPLOYPATH/Config/
    - /bin/cp /home/u1525344/repositories/tpqsmart/app/Config/Autoload.php $DEPLOYPATH/Config/
    - /bin/cp /home/u1525344/repositories/tpqsmart/app/Config/Filters.php $DEPLOYPATH/Config/
    - /bin/cp /home/u1525344/repositories/tpqsmart/app/Config/Services.php $DEPLOYPATH/Config/
    - /bin/cp /home/u1525344/repositories/tpqsmart/app/Helpers/js/image-upload-helper.js $DEPLOYPATH/Helpers/js/
    - /bin/cp /home/u1525344/repositories/tpqsmart/app/Controllers/Helpers.php $DEPLOYPATH/Controllers/

