---
deployment:
  tasks:
    - export DEPLOYPATH=/home/u1525344/tpqsmart/app
    - /bin/cp -r /home/u1525344/repositories/tpqsmart/app/Models $DEPLOYPATH
    - /bin/cp -r /home/u1525344/repositories/tpqsmart/app/Views $DEPLOYPATH
    - /bin/cp -r /home/u1525344/repositories/tpqsmart/app/Controllers $DEPLOYPATH
    - /bin/cp /home/u1525344/repositories/tpqsmart/app/Config/Routes.php $DEPLOYPATH/Config/

