---
deployment:
  tasks:
    # TPQ Smart deployment
    - export DEPLOYPATH=/home/u1525344/tpqsmart/app
    - /bin/cp -r /home/u1525344/repositories/tpqsmart/app/Models $DEPLOYPATH
    - /bin/cp -r /home/u1525344/repositories/tpqsmart/app/Views $DEPLOYPATH
    - /bin/cp -r /home/u1525344/repositories/tpqsmart/app/Controllers $DEPLOYPATH
    - /bin/cp /home/u1525344/repositories/tpqsmart/app/Config/Routes.php $DEPLOYPATH/Config/

    # Daftar Santri Baru deployment
    - export DEPLOYPATH1=/home/u1525344/daftarsantribaru/app
    - /bin/cp /home/u1525344/repositories/tpqsmart/app/Models/SantriBaruModel.php $DEPLOYPATH1/Models/SantriBaruModel.php
    - /bin/cp /home/u1525344/repositories/tpqsmart/app/Models/HelpFunction.php $DEPLOYPATH1/Models/HelpFunction.php
    - /bin/cp /home/u1525344/repositories/tpqsmart/app/Controllers/Backend/Santri.php $DEPLOYPATH1/Controllers/Backend/Santri.php
    - /bin/cp /home/u1525344/repositories/tpqsmart/app/Views/backend/santri/createEmisStep.php $DEPLOYPATH1/Views/backend/santri/createEmisStep.php
    - /bin/cp /home/u1525344/repositories/tpqsmart/app/Views/backend/santri/listSantriBaru.php $DEPLOYPATH1/Views/backend/santri/listSantriBaru.php
    - /bin/cp /home/u1525344/repositories/tpqsmart/app/Views/backend/santri/listSantriBaruPerKelasTpq.php $DEPLOYPATH1/Views/backend/santri/listSantriBaruPerKelasTpq.php  